@isTest
public class DummyClassTest{
    public static testMethod void DummyMethodCall(){
        DummyClass obj1 = new DummyClass();
        obj1.dummyMethod();
        DummyClass1 obj2 = new DummyClass1();
        obj2.dummyMethod();
        DummyClass2 obj3 = new DummyClass2();
        obj3.dummyMethod();
        DummyClass3 obj4 = new DummyClass3();
        obj4.dummyMethod();
        DummyClass4 obj5 = new DummyClass4();
        obj5.dummyMethod();
        DummyClass6 obj6 = new DummyClass6();
        obj6.dummyMethod();
        DummyClass7 obj7 = new DummyClass7();
        obj7.dummyMethod();
        DummyClass8 obj8 = new DummyClass8();
        obj8.dummyMethod();
    }

}